language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio
- platformio lib --global install mbino

env:
- BOARD=uno
- BOARD=leonardo
- BOARD=megaatmega2560

script:
- set -eo pipefail;
  for e in examples/*/*.ino; do
    platformio ci --board=$BOARD --lib=. $e;
  done
