language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio
- platformio lib --global install mbino

env:
- PLATFORMIO_CI_SRC=examples/DataLogger
- PLATFORMIO_CI_SRC=examples/StartLight

script:
- platformio ci --lib="." --board=uno --board=leonardo
- platformio ci --lib="src" --board=nucleo_f446re
